include $(FUZIX_ROOT)/Target/rules.68000

SRCS  = netd.c uip.c uiplib.c timer.c clock-arch.c uip_arp.c telnet.c
SRCS += echoping.c dig.c gethostbyname.c httpd.c ping.c ntpdate.c
SRCS += htget.c tinyirc.c linein.c ifconfig.c

OBJS = $(SRCS:.c=.o)

APPS = telnet echoping dig httpd ping ntpdate htget tinyirc ifconfig

CFLAGS += -DNETD_BIG_ENDIAN

all: $(APPS)

telnet: $(CRT0) telnet.o gethostbyname.o
	$(LINKER) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)

echoping: $(CRT0) echoping.o
	$(LINKER) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)

dig: $(CRT0) dig.o
	$(LINKER) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)

httpd: $(CRT0) httpd.o
	$(LINKER) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)

ping: $(CRT0) ping.o gethostbyname.o
	$(LINKER) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)

ntpdate: $(CRT0) ntpdate.o gethostbyname.o
	$(LINKER) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)

htget:	$(CRT0) htget.o gethostbyname.o
	$(LINKER) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)

tinyirc: $(CRT0) tinyirc.o linein.o gethostbyname.o
	$(LINKER) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)

ifconfig: $(CRT0) ifconfig.o linein.o gethostbyname.o
	$(LINKER) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report *~

rmbak:
	rm -f *~ core
